### ISSUE TITLE
Create preliminary FBD and loading analysis

### ISSUE THREAD

**Issue by MFauzanAP** [QU-RoboSub/2025-mechanical#19]
Requires assumptions about the environment to be made from #2 and an initial thruster to be chosen from #6,

**Comment by MFauzanAP** [comment]
I think the forces acting on the AUV during movement will be:
- Thrust force
- Hydrodynamic drag
- Weight
- Buoyancy

But I don't think the AUV should be modelled as a particle, but instead as a solid body where the forces are acting on different points, since the center of mass, center of buoyancy, and thrusters will not be aligned.

Also, how will we model the AUV going in different directions or rotating? Since there will be multiple thrusters should we model each one separately or just consider the overall force? Should we create multiple FBDs for each degree of freedom?

**Comment by khalidbelkhair** [comment]
I agree, modelling the AUV as a particle is definitely not an option. This is mainly as we also need to consider the rotation, which we can't do with the assumption of the particle. Though, in my opinion, we only need to consider the rotation through the y & z axis (as in the picture) to be free, while the rotation through the x-axis just needs to be maintained balanced. In that case, the structure can be considered as a beam (which is able to consider all translating degrees of motion, with the two required rotation degrees of motion).

I have attached a picture with the initial Free Body Diagram. I have split it into two main components/system:

- System 1 (Balance): This will mainly look at the weight and the buoyant forces. Of course, the aim here is to have a neutral buoyancy. **Also**, it is important to make sure that the buoyant force is applied at the center of mass (to directly cancel out with the weight of the AUV). To do this, we definitely need to consider buoyancy control systems at two (or more) positions (e.g. front and back), to be able to control the position of the net buoyant force. **_If achieved_**, the AUV will maintain its position (as well as elevation), given that no further external forces are applied.
- System 2 (Control): This will involve the forces of all the thrusters (any propulsion system), which will be positioned aligning to all axes (x, y, & z). Given the system has a neutral buoyancy, the thrusters will easily be able to control the translation (through all axes) and the rotations through the y & z axes (as per the diagram). 
- It is also important to consider the currents and the hydrodynamic drag (whilst in motion). This will mainly effect system 2 (control).

![Image](https://github.com/QU-RoboSub/2025-mechanical/assets/170858943/bb3c002e-058b-4475-b8cd-6cfca5bef985)

**Comment by khalidbelkhair** [comment]
It is also a viable option to use thrusters that are positioned at a 45 degree (between the x & z axes). This can be replace the thrusters that are positioned at the z-axis (in the diagram before). 
- The main benefit of this is the ability to quickly rotate about the y-axis, while remaining in place with minimal translation.

**Comment by MFauzanAP** [comment]
Looks like a great start overall masyaAllah, easy to understand working and very well drawn figures. Although I have a few comments for discussion:

For clarity, would it be possible to rename the axis names with the ones from here:

![Image](https://github.com/QU-RoboSub/2025-mechanical/assets/85939000/5bea3b9a-5b5d-4e11-984b-dd7af1137f63)

It's a bit confusing to see where the different axes are and the direction of moments, but using the above standard will make it much simpler imo. Basically:
- Surge is moving forward
- Sway is moving side-to-side
- Heave is up and down
- Roll is rolling along the surge axis
- Yaw is changing the forward direction
- Pitch is rotating up and down

> Also, it is important to make sure that the buoyant force is applied at the center of mass

Regarding this, the buoyant force is applied at the center of buoyancy (COB) which is different from the center of mass (COM), see [the first two lines on this website](https://www.engineeringtoolbox.com/centre-gravity-buoyancy-d_1286.html) and from the book:

> An object's center of buoyancy is located where its center of gravity would be if the object had a perfectly uniform distribution of mass, which is almost never the case ... Then the CoB of the object is the center of gravity of the object-shaped blob of water

Also, usually we want the CoB to be directly above the CoM so that when the AUV is slightly tilted, it will automatically try to orient itself in the right direction. This is why in some AUVs they have the buoyancy foam at the top and the ballast weights at the bottom.

![Image](https://github.com/QU-RoboSub/2025-mechanical/assets/85939000/f5d9546c-a763-47c3-b7c9-6b5bf0f2cfc3)

**Comment by MFauzanAP** [comment]
But again, it seems like good progress for the weekend submission alhamdulillah. The next steps would be to take this further and use a mathematical model to describe the motion of the AUV w.r.t. thruster, buoyant, weight, drag, and ocean-current forces. I've been doing a bit of reading on this and I'm quite excited to start working on it, it seems very interesting.

**Comment by khalidbelkhair** [comment]
Yes exactly, thank you for the comments.

> For clarity, would it be possible to rename the axis names with the ones from here:

This will most definitely make the discussion easier to follow. Let's all stick with these terms.

> Also, usually we want the CoB to be directly above the CoM

Definitely, but keep in mind that if we do so, we will limit the ability of the AUV to pitch. In my opinion, the advantages of keeping a stable (and level) AUV outweighs the need for it to pitch. 

- Though, keep in mind that for the AUV to remain level, the CoB needs to be above the CoM, or else the AUV will have a natural position to be tilted. This is why I have suggested a buoyancy control system at 2 or more positions; besides the purpose of adjusting the buoyancy of the AUV, it will also adjust it's CoM to be in-line with the CoB. I have attached a picture to demonstrate the concept.

![Image](https://github.com/QU-RoboSub/2025-mechanical/assets/170858943/ca277512-37bf-4e0e-90bc-b6976b943bbe)

Of course there are many different ways to go about this problem, which still needs to be further studied. 

> The next steps would be to take this further and use a mathematical model to describe the motion of the AUV

Agreed. Though I am not too sure regarding how deep we should go into this at this stage, as to me it seems a bit too early.

**Comment by MFauzanAP** [comment]
> I have attached a picture to demonstrate the concept.

This is a nice idea, but initially, I was thinking of using only the thrusters as a form of active control over the orientation of the vehicle, whilst the buoyancy tanks/foam would just be there for passive control (refer to what I mentioned about automatic self-righting).

The reason I went for this initially is because its a lot simpler in terms of control, manufacture and mathematical modelling, and cheaper as well since we don't need to buy another actuator to handle the opening and closing of the buoyancy tanks. The PID controls would take care of self-levelling and changing pitch or roll if needed by supplying more power to the appropriate thrusters.

Let me know what you think of this.

> Agreed. Though I am not too sure regarding how deep we should go into this at this stage, as to me it seems a bit too early.

Yes, very good point. I guess for the submission this weekend, we can just stick with a simple free body diagram showing what kind of forces we're expecting. 

Then, we can do an initial analysis by assuming the mass, volume, and target speed of the AUV, and the drag coefficient of the water to calculate how much thrust our thruster should provide. From here, I guess we can try to pick some thrusters.

The values for these parameters can be found from the handbook, specifications from the literature survey Excel sheet, and some general online research. If you need some additional help with some things, feel free to let me know.

**Comment by khalidbelkhair** [comment]
> I was thinking of using only the thrusters as a form of active control over the orientation of the vehicle

Of course the thrusters will have control over the vehicle, but keep in mind that what I am referring to is the natural position of the AUV. Meaning, that without proper control of the center of mass of the vehicle, the CoM will most likely not align with the CoB, resulting in the vehicle having a tendency to be at a tilted position. From what I understood from your idea (correct me if I am wrong), is to control this by using the thrusters (which in this case will need to be constantly working to apply the balancing forces). The main problem I see if this is that the AUV will have a naturally titled position (which is not sustainable), besides the fact that the constant working of the thrusters will drain the batteries. We will also have to keep the the UAV fairly balanced as well, as there will definitely be a limit as to how much the thrusters can balance the vehicle.

This is definitely a key component that will effect the final design, hence further research needs to be done. Though, please feel free to add any further comments regarding this.

**Comment by khalidbelkhair** [comment]
Perfect. Let's keep all these options for the morphological chart in #14.
Definitely a good start on this problem.

**Comment by MFauzanAP** [comment]
Closing this as done, initial analysis will be done at a later time
