### ISSUE TITLE
Write problem definition document

### ISSUE THREAD

**Issue by MFauzanAP** [QU-RoboSub/2025-mechanical#4]
Refer to the following rubric items when writing this document. Document link can be found [here](https://qucloud.sharepoint.com/:w:/r/sites/UnderWaterVehicleMSDP/Shared%20Documents/General/Mechanical%20Engineering/Phase%20I%20-%20Product%20Definition/Problem%20Definition.docx?d=we41927a0fef04313b61ee8435187792b&csf=1&web=1&e=8guNQP)

<table>
    <thead>
        <tr>
            <th>Requirements</th>
            <th>Action Item</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Is able to define unfamiliar problems. </td>
            <td rowspan=2>Write a short background on the problem (need for robots for marine research and it's impact) and write a short paragraph talking about our solution to this problem (ie manufacture an AUV) <br><br> List the different objectives the project will need to meet in terms of technicality, such as creating the propulsion, buoyancy, payload systems, etc. </td>
        </tr>
        <tr>
            <td>Fully comprehends the question, problem, or issue to be addressed. </td>
        </tr>
        <tr>
            <td>Excellent prediction of impact on all applicable factors with in-depth discussion</td>
            <td rowspan=2>Create a dedicated section about the impact of project (or AUVs in general) on marine research, oil & gas industry, climate preservation, etc</td>
        </tr>
        </tr>
            <td>Able to identify and give a comprehensive explanation of the impact of 
engineering solutions with respect to global, economic, environmental, and societal contexts. </td>
        </tr>
    </tbody>
</table>

**Comment by khalidbelkhair** [comment]
@NazarulYousef Please also consider the discussion made in #19.

Main points from the discussion:
- The use of the accurate terms to discuss the motion of the AUV ([here](https://github.com/QU-RoboSub/2025-mechanical/issues/19#issuecomment-2137252390))
- Describing the control of the AUV into two main sub-systems (balance & active motion) ([here](https://github.com/QU-RoboSub/2025-mechanical/issues/19#issuecomment-2137200186))
- The rest of the discussion was looking into ways to create a proper balance system for the AUV, in terms of the CoM (center of mass) and the CoB (center of buoyancy).

**Comment by MFauzanAP** [comment]
The document looks good, great job with this brother. I've made some minor formatting changes and removed one of the technical objectives to fit for mechanical engineering only.

I'll be moving this task to the `done` category
